### ISSUE TITLE
Occasional (1/9) test failure on test_qspi_flash_fast_read_calibrate.c

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_qspi_fast_read#29]
This issue passes on a re-run but looks like an intermittent failure (about 1 in 9) on the unit tests:
 
test_qspi_flash_fast_read_calibrate.c at lines [38](https://github.com/xmos/lib_qspi_fast_read/blob/ffbbf8dffee5ed4eac07454d7e985f3c65de8e37/test/ci/api/src/api_coverage/test_qspi_flash_fast_read_calibrate.c#L38) and [57](https://github.com/xmos/lib_qspi_fast_read/blob/ffbbf8dffee5ed4eac07454d7e985f3c65de8e37/test/ci/api/src/api_coverage/test_qspi_flash_fast_read_calibrate.c#L57)
and sometimes
test_qspi_flash_fast_read.c at line [44](https://github.com/xmos/lib_qspi_fast_read/blob/ffbbf8dffee5ed4eac07454d7e985f3c65de8e37/test/ci/api/src/api_coverage/test_qspi_flash_fast_read.c#L44)
 
The second is likely a consequence of the first.
 
I am not sure yet if it is related to an agent (they only run on VRDs of which there two) but seems to be a failure to calibrate the flash from the training pattern and so the function fails to find suitable delay settings. I think it would take a bit bench investigation with the HW to recreate. I'd want to put a day aside to investigate this initially.

**Comment by mbanth** [comment]
This issue is tracked in Jira [AP-240](https://xmosjira.atlassian.net/browse/AP-240).

[AP-240]: https://xmosjira.atlassian.net/browse/AP-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
